///**************new updated code**************************

pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            //INcase on new version just change the 16 to that new version number
            // Optionally you can specify additional configurations like `args` (to pass Docker arguments)
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'  // This will run the `node --version` command inside the Docker container
            }
        }
    }
}



// pipeline {
//   agent {
//     docker { image 'node:16-alpine' }
//   }
//   stages {
//     stage('Test') {
//       steps {
//         sh 'node --version'
//       }
//     }
//   }
// }
